[package]
name = "cmdmat"
version = "0.1.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "cmdmat"
path = "lib.rs"

[dependencies]
either = "1.5.0"
smallvec = "0.6.9"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
