[package]
name = "gameshell"
version = "0.1.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmdmat = { path = "crates/cmdmat" }
either = "1.5.0"
metac = { path = "crates/metac" }
quickcheck = "0.8"
quickcheck_macros = "0.8"
rand = "0.6"
regex = "1.1.7"

[dev-dependencies]
criterion = "0.2"
crossbeam-channel = "0.3.8"

[[bench]]
name = "basic"
harness = false
