[package]
name = "metac"
version = "0.0.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "metac"
path = "lib.rs"

[dependencies]
smallvec = "0.6.10"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "basic"
harness = false
