[package]
name = "metac"
version = "0.0.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "metac"
path = "lib.rs"

[dependencies]
smallvec = "0.6.9"
